name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  collectInputs:
    name: Collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.14.0

  preCommit:
    name: Pre-commit
    needs: collectInputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Terraform min/max versions
        id: minMax
        uses: ./
        with:
          directory: ${{ matrix.directory }}

      # Min version
      - name: Remove default Terraform
        run: rm -rf $(which terraform)

      - name: Install Terraform ${{ steps.minMax.outputs.minVersion }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.minMax.outputs.minVersion }}

      - name: Terraform validate ${{ steps.minMax.outputs.minVersion }}
        working-directory: ${{ matrix.directory }}
        run: |
          terraform init
          terraform validate

      # Max version
      - name: Remove min Terraform
        run: rm -rf $(which terraform)

      - name: Install Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.minMax.outputs.maxVersion }}

      - name: Terraform validate ${{ steps.minMax.outputs.maxVersion }}
        working-directory: ${{ matrix.directory }}
        run: |
          terraform init
          terraform validate
